FROM python:3.8-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential gcc ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY ./src/pymp_common/ ./pymp_common
COPY ./src/pymp_media_svc/ ./pymp_media_svc

RUN pip3 install ./pymp_common
RUN pip3 install ./pymp_media_svc

CMD ["python", "-u", "-m" , "pymp_media_svc"]