---
version: "3.9"
services:
  pymp_frontend:
    image: pymp_frontend
    ports:
      - "8080:80"
    env_file:
      - 'common.env'
    networks:
      - fe_public
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: unless-stopped

  pymp_frontend_api:
    image: pymp_frontend_api
    env_file:
      - 'common.env'
    networks:
      - fe_public
      - be_public
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: unless-stopped

  pymp_media_svc:
    image: pymp_media_svc
    env_file:
      - 'common.env'
    networks:
      - be_public
    volumes:
      - /srv/media/videos:/app/videos:ro
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 250M
    restart: always

  pymp_ffmpeg_svc:
    image: pymp_ffmpeg_svc
    env_file:
      - 'common.env'
    networks:
      - be_public
    volumes:
      - /srv/media/videos:/app/videos:ro
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 50M
    restart: always

  redis:
    image: redis:7-alpine
    networks:
      - be_public
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - /srv/media/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 250M
    restart: always

  # pymp_file_svc:
  #   image: pymp_file_svc
  #   env_file:
  #     - 'common.env'
  #   networks:
  #     - fe_admin
  #   ports:
  #     - "8082:80"
  #   volumes:
  #     - /srv/media/videos:/files:rw
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 50M
  #       reservations:
  #         cpus: '0.5'
  #         memory: 20M
  #   restart: unless-stopped

networks:
  fe_public:
  be_public:
  fe_admin: