---
version: "3.9"
services:

  # PYMP Services
  pymp_frontend:
    image: pymp_frontend
    ports:
      - "8080:80"
    env_file:
      - 'frontend.env'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: unless-stopped

  pymp_frontend_media_api:
    image: pymp_server
    ports:
      - "8081:80"
    env_file:
      - 'server_api.env'
    environment:
      - SERVER_TYPE=1
    networks:
      - fe_api_svc
      - be_api_svc
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: unless-stopped

  pymp_frontend_thumb_api:
    image: pymp_server
    ports:
      - "8082:80"
    env_file:
      - 'server_api.env'
    environment:
      - SERVER_TYPE=4
    networks:
      - fe_api_svc
      - be_api_svc
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: unless-stopped

  pymp_frontend_meta_api:
    image: pymp_server
    ports:
      - "8083:80"
    env_file:
      - 'server_api.env'
    environment:
      - SERVER_TYPE=2
    networks:
      - fe_api_svc
      - be_api_svc
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: unless-stopped

  pymp_media_svc:
    image: pymp_server
    env_file:
      - 'server_svc.env'
    environment:
      - SERVER_TYPE=8
      - SERVER_ID=first
      - MEDIA_SVC_HOST=pymp_media_svc
    networks:
      - fe_api_svc
      - be_api_svc
    ports:
      - "8880:80"
    volumes:
      - /srv/media/videos:/app/media:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 250M
    restart: always

  pymp_mediaregistry_svc:
    image: pymp_server
    env_file:
      - 'server_svc.env'
    environment:
      - SERVER_TYPE=32
    networks:
      - fe_api_svc
      - be_api_svc
    ports:
      - "8085:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 50M
    restart: always

  pymp_ffmpeg_svc:
    image: pymp_server
    env_file:
      - 'server_svc.env'
    environment:
      - SERVER_TYPE=16
    networks:
      - be_api_svc
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 50M
    restart: always

  pymp_file_svc:
    image: pymp_file_svc
    networks:
      - be_api_svc
    env_file:
      - 'server_api.env'
    ports:
      - "8087:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.5'
          memory: 20M
    restart: unless-stopped

  # Redis Services
  redis-slave:
    image: redis:latest
    command: redis-server --slaveof redis-master 6379
    networks:
      - fe_api_svc
      - be_redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: always
   
  redis-master:
    image: redis:latest
    command: redis-server --port 6379   
    networks:
      - be_api_svc
      - be_redis
    volumes: 
      - /srv/media/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: always

networks:
  fe_api_svc:
  be_api_svc:
  be_redis: