FROM busybox:latest

RUN adduser -D static

WORKDIR /home/static
COPY --chown=static:static ./src/pymp_frontend/templates/ templates/
COPY --chown=static:static ./src/pymp_frontend/entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

USER static

CMD ["/home/static/entrypoint.sh"]