{
 "title": "Default",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "FfmpegDataProvider Get Meta/Thumb Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pymp_core_providers_ffmpegfiledataprovider_get_meta_seconds_total[15m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pymp_core_providers_ffmpeghttpdataprovider_get_meta_seconds_total[15m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pymp_core_providers_ffmpegfiledataprovider_get_thumb_seconds_total[15m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pymp_core_providers_ffmpeghttpdataprovider_get_thumb_seconds_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MediaService GetMediaChunk Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaservice_get_media_chunk_seconds_total[15m])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MediaDataProvider Get Media Chunk Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_providers_mediafiledataprovider_get_media_chunk_seconds_total[15m])",
     "legendFormat": "MediaFileDataProvider"
    },
    {
     "expr": "rate(pymp_core_providers_mediahttpdataprovider_get_media_chunk_seconds_total[15m])",
     "legendFormat": "MediaHttpDataProvider"
    }
   ]
  },
  {
   "title": "MediaService GetMediaThumb Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaservice_get_media_thumb_seconds_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MediaService GetMediaMeta Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaservice_get_media_meta_seconds_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}