{
 "title": "Pymp Services",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "MediaRegistry Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MediaRegistry GetRegisteredServices Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaregistryservice_get_registered_services_seconds_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MediaRegistry GetMediaInfo Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaregistryservice_get_media_info_seconds_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MediaRegistry GetMediaIndex Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaregistryservice_get_media_index_seconds_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MediaRegistry RegisterService Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaregistryservice_register_service_seconds_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Media Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "MediaRegistry GetMediaIndex Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaregistryservice_get_media_index_seconds_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MediaService GetMediaThumb Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaservice_get_media_thumb_seconds_total[15m])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MediaService GetMediaIds Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaservice_get_media_ids_seconds_total[15m])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MediaService GetMediaChunk Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaservice_get_media_chunk_seconds_total[15m])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MediaService GetMediaMeta Seconds [15m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_mediaservice_get_media_meta_seconds_total[15m])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "Ffmpeg Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "FfmpegService ProcessMediaThumb [15m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_ffmpegservice_process_media_thumb_seconds_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FfmpegService ProcessMediaMeta [15m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pymp_core_services_ffmpegservice_process_media_meta_seconds_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}