ARG BASE_IMAGE=ghcr.io/tomp736/pyfi/pyfi_core:latest
FROM $BASE_IMAGE

ARG APP_BUILD_VERSION
ENV APP_BUILD_VERSION ${APP_BUILD_VERSION}

RUN mkdir -p /app/media
RUN mkdir -p /app/index

COPY ./pymp_server/ ./pymp_server
RUN pip3 install ./pymp_server

CMD ["python", "-u", "-m" , "pymp_server"]