FROM ghcr.io/labrats-work/ops-images/python:latest

COPY ./src/pymp_core/ ./pymp_core
RUN pip3 install ./pymp_core

COPY ./src/pymp_server/ ./pymp_server
RUN pip3 install ./pymp_server

CMD ["python", "-u", "-m" , "pymp_server"]