ARG BASE_IMAGE=ghcr.io/tomp736/pyfi/pyfi_core:latest
ARG APP_BUILD_VERSION

FROM $BASE_IMAGE as base

RUN pip3 install --upgrade pip

FROM base as build
WORKDIR /src

ENV APP_BUILD_VERSION ${APP_BUILD_VERSION}

COPY ./pymp_server/requirements.txt ./pymp_server/
RUN pip3 install --no-cache-dir -r ./pymp_server/requirements.txt 

COPY ./pymp_server/ ./pymp_server
RUN pip3 install --no-cache-dir ./pymp_server

CMD ["python", "-u", "-m" , "pymp_server"]