name: Dispatch_Deployment_Workflow
description: dispatches deployment

inputs:
  environment:
    type: string
    description: 'Environment to deploy'
    required: true
  version:
    type: string
    description: 'App version to deploy'
    required: true
  dispatch_token:
    type: string
    description: 'GitHub token to trigger dispatch'
    required: true

jobs:
  dispatch-deployment-job:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Prepare Dispatch Payload
        run: |
          cat <<EOF > payload.json
          {
            "event_type": "patch_pymp",
            "client_payload": {
              "environment": "${{ inputs.environment }}",
              "version": "${{ inputs.version }}",
              "message": "Update pymp deployment."
            }
          }
          EOF

      - name: Trigger Repository Dispatch
        run: |
          curl -X POST \
              -H "Authorization: Bearer ${{ inputs.dispatch_token }}" \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Content-Type: application/json" \
              --data @payload.json \
              https://api.github.com/repos/tomp736/pymp_infra_flux/dispatches
