ARG BASE_IMAGE=ghcr.io/labrats-work/ops-images/python-ffmpeg:latest
FROM $BASE_IMAGE

ARG APP_BUILD_VERSION
ENV APP_BUILD_VERSION ${APP_BUILD_VERSION}

COPY ./pymp_core/ ./pymp_core
RUN pip3 install ./pymp_core

COPY ./pymp_core_tests/ ./pymp_core_tests/
RUN pip3 install -r ./pymp_core_tests/requirements.txt
RUN pytest ./pymp_core_tests/