ARG BASE_IMAGE=python:3.9-slim
ARG APP_BUILD_VERSION

FROM $BASE_IMAGE as base

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential gcc ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

FROM base as build
WORKDIR /src

ENV APP_BUILD_VERSION ${APP_BUILD_VERSION}

COPY ./pymp_core/requirements.txt ./pymp_core/
RUN pip3 install --no-cache-dir -r ./pymp_core/requirements.txt 

COPY ./pymp_core/ ./pymp_core
RUN pip3 install --no-cache-dir ./pymp_core

FROM build as test
WORKDIR /src

COPY ./pymp_core_tests/requirements.txt ./pymp_core_tests/
RUN pip3 install --no-cache-dir -r ./pymp_core_tests/requirements.txt 

COPY ./pymp_core_tests/ ./pymp_core_tests
RUN pytest ./pymp_core_tests


FROM build as final
WORKDIR /src