---
version: "3.3"
services:

  # PYMP Services
  pymp-frontend:
    image: pymp_frontend
    ports:
      - "8080:80"
    environment:
      MEDIA_URL: "http://localhost:8081/api"
      THUMB_URL: "http://localhost:8081/api"
      META_URL: "http://localhost:8081/api"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: unless-stopped

  pymp-server:
    image: pymp_server
    ports:
      - "8081:80"
    environment:
      PYTHONHASHSEED: "383747829"
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: "80"
      FLASK_CORS_HEADERS: "*"
      REDIS_HOST: "pymp-redis-readonly"
      REDIS_PORT: "6379"
      MEDIA_MEDIA_CHUNK_SIZE: "4194304"
      MEDIA_THUMB_CHUNK_SIZE: "32768"
      MEDIA_MEDIA_PATH: "/data/media"
      MEDIA_INDEX_PATH: "/data/index"
      SERVER_PROTO: "http"
      SERVER_HOST: "pymp-server"
      SERVER_PORT: "80"
      SERVER_ROLES: "30"
    volumes: 
      - ./registry-services.json:/app/registry-services.json
    networks:
      - media_net
      - redis_fe
      - locust_net
      - prom_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: unless-stopped
  
  pymp-server-media-registry:
    image: pymp_server
    environment:
      PYTHONHASHSEED: "383747829"
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: "80"
      FLASK_CORS_HEADERS: "*"
      REDIS_HOST: "pymp-redis"
      REDIS_PORT: "6379"
      SERVER_PROTO: "http"
      SERVER_HOST: "pymp-server-media-registry"
      SERVER_PORT: "80"
      SERVER_ROLES: "64"
    volumes: 
      - ./registry-services.json:/app/registry-services.json
    networks:
      - media_net
      - redis_be
      - prom_net
    ports:
      - "8085:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 50M
    restart: always

  pymp-server-ffmpeg:
    image: pymp_server
    environment:
      PYTHONHASHSEED: "383747829"
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: "80"
      FLASK_CORS_HEADERS: "*"
      REDIS_HOST: "pymp-redis"
      REDIS_PORT: "6379"
      MEDIA_MEDIA_CHUNK_SIZE: "4194304"
      MEDIA_THUMB_CHUNK_SIZE: "32768"
      SERVER_PROTO: "http"
      SERVER_HOST: "pymp-server-ffmpeg"
      SERVER_PORT: "80"
      SERVER_ROLES: "32"
    volumes: 
      - ./registry-services.json:/app/registry-services.json
    networks:
      - media_net
      - redis_be
      - prom_net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 50M
    restart: always

 # Redis Services   
  pymp-redis:
    image: redis:latest
    command: redis-server --port 6379   
    networks:
      - redis_be
    volumes: 
      - /srv/pymp/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: always

  pymp-redis-readonly:
    image: redis:latest
    command: redis-server --slaveof pymp-redis 6379
    networks:
      - redis_fe
      - redis_be
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 25M
    restart: always

  # # Monitoring and Load Testing Services
  # prometheus:
  #   image: prom/prometheus
  #   networks:
  #     - prom_net
  #   ports:
  #     - 9090:9090
  #   volumes: 
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - /srv/pymp/prometheus:/prometheus:rw
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 100M
  #       reservations:
  #         cpus: '0.5'
  #         memory: 100M
  #   restart: always
    
  # grafana:
  #   image: grafana/grafana:latest
  #   networks:
  #     - prom_net
  #   ports:
  #     - 9091:3000
  #   volumes: 
  #     - ./grafana/dashboards:/etc/dashboards
  #     - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
  #     - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
  #     - /srv/pymp/grafana:/var/lib/grafana:rw
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 100M
  #       reservations:
  #         cpus: '0.5'
  #         memory: 100M
  #   restart: always

  # pymp-locust:
  #   image: ghcr.io/tomp736/pymp/pymp_locust:latest-dev
  #   networks:
  #     - locust_net
  #   ports:
  #     - "8089:8089"
  #   env_file:
  #     - 'locust.env'
  #   command: -f /mnt/locust/locustfiles  

networks:
  prom_net: 
  locust_net:
  redis_be:
  redis_fe:
  media_net: