FROM busybox:latest

ARG APP_BUILD_VERSION
ENV APP_BUILD_VERSION ${APP_BUILD_VERSION}

RUN adduser -D static

WORKDIR /home/static
COPY --chown=static:static ./pymp_frontend/templates/ templates/
COPY --chown=static:static ./pymp_frontend/entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

USER static

CMD ["/home/static/entrypoint.sh"]