name: Create PR

on:
  workflow_call:
    inputs:
      source_branch:
        type: string
        description: 'source branch name'
        required: true
      target_branch:
        type: string
        description: 'target branch name'
        required: true

  workflow_dispatch:
    inputs:
      source_branch:
        type: string
        description: 'source branch name'
        required: true
      target_branch:
        type: choice
        description: 'target branch name'
        default: dev
        options:
          - dev
          - main
        required: true

jobs:
  create_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Reset promotion branch
        run: |
          git fetch origin ${{ github.event.inputs.source_branch }}:${{ github.event.inputs.source_branch }}
          git reset --hard ${{ github.event.inputs.source_branch }}

      - name: Create PR
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          branch: ${{ github.event.inputs.target_branch }}-promotion

      # See: https://github.com/peter-evans/create-pull-request/tree/main#auto-merge
      # - name: enable auto-merge
      #   if: steps.create_pull_request.outputs.pull-request-operation == 'created'
      #   uses: peter-evans/enable-pull-request-automerge@v2
      #   with:
      #     token: ${{ secrets.PAT }}
      #     pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
      #     merge-method: squash