name: create tag

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'version'
        required: true
jobs:
  create_tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
      - run: |      
          git tag ${{ inputs.version }}
          git push -f origin --tags