name: 'cron cleanup images'

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  delete-slow:
    runs-on: ubuntu-latest
    steps:
      - name: list image tags
        run: |
          # https://ghcr.io/tomp736/pymp/pymp_core/tags
          registry_server="ghcr.io"
          user="tomp736"
          image="pymp/pymp_core"

          TAGS=$(curl -H "Authorization: Bearer ${{ secrets.READ_IMAGES }}" \
              -H "Accept: application/json" \
              "https://$registry_server/v2/$user/$image/tags/list?n=500" | jq -r '.tags[]')

          for tag in $TAGS; do
            if [[ "$tag" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Tag valid: $user/$image:$tag"
            elif [[ "$tag" = 'latest' ]]; then
              echo "Tag valid: $user/$image:$tag"
            else
              echo "Tag invalid: $user/$image:$tag"
              curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.DELETE_IMAGES }}" \
                "https://$registry_server/v2/$user/$image/manifests/$tag"
            fi
          done

