name: 'cron cleanup images'

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  delete-slow:
    runs-on: ubuntu-latest
    steps:
      - name: list image tags
        run: |
          # https://ghcr.io/tomp736/pymp/pymp_core/tags
          registry_server="ghcr.io"
          user="tomp736"
          image="pymp/pymp_core"
          image_encoded="pymp%2Fpymp_core"

          TAGS=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.READ_IMAGES }}" \
              https://api.github.com/users/$user/packages/container/$image_encoded/versions \
              | jq -r '.[] | [.name, .metadata.container.tags[] // "" ] | @csv')

          for tag in $TAGS; do
            if [[ "$tag" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Tag valid: $user/$image:$tag"
            elif [[ "$tag" = 'latest' ]]; then
              echo "Tag valid: $user/$image:$tag"
            else
              echo "Tag invalid: $user/$image:$tag"

              curl -L \
                -X DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.DELETE_IMAGES }}" \
                https://api.github.com/users/$user/packages/container/$image_encoded/versions/$tag
            fi
          done

