name: 'on pr open src'

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - dev
      - main
    paths:
      - "src/**"

jobs:
  
  # run tests
  tests:
    uses: ./.github/workflows/on_wfc_tests.yml
    secrets: inherit

  # run the docker_build_push workflow
  docker_build_push:
    needs:
      - tests

    permissions:
      contents: read
      packages: write
      
    uses: ./.github/workflows/docker_build_push.yml
    with:
      registry: ghcr.io
      repository: ${{ github.repository }}
      build_tag: ${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.number }}-${{ github.event.pull_request.commits }}
    secrets: inherit

  # issue repository dispatch
  dispatch_deployment:

    needs:
      - docker_build_push
      
    uses: ./.github/workflows/on_wfc_dispatch_deployment.yml
    with:
      environment: ${{ github.event.pull_request.head.ref }}
      version: ${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.number }}-${{ github.event.pull_request.commits }}
    secrets: inherit