name: on branch push
on: 
  workflow_dispatch:    
  push:
    branches:
      - '**'
      - '!*-promotion'

jobs:

  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      pull_request_create: ${{ steps.pull_request.outputs.pull_request_create }}
      pull_request_branch_target: ${{ steps.pull_request.outputs.pull_request_branch_target }}
      pull_request_branch_source: ${{ steps.pull_request.outputs.pull_request_branch_source }}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      # Adds variables related to version using output from git ls-remote
      # this_version: { semantic version } latest version from git ls-remote
      # next_version: { semantic version } latest version incremented based on branch name
      - id: versions
        shell: bash
        run: |
          this_version=$(git ls-remote --tag origin | cut -d '/' -f 3 | sort -V | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)

          major=$(echo $this_version | awk -F'.' '{print $1}')
          minor=$(echo $this_version | awk -F'.' '{print $2}')
          patch=$(echo $this_version | awk -F'.' '{print $3}')
          patch_iter=""

          if [[ "${{ github.ref }}" = "refs/heads/main" ]]; then
            minor=$((minor+1))
            patch=0
          elif [[ "${{ github.ref }}" = "refs/heads/dev" ]]; then
            patch=$((patch+1))
          else
            patch_count=$(git ls-remote --tag origin | cut -d '/' -f 3 | sort -V | grep $major.$minor.$patch | wc -l)
            patch_iter="-$patch_count"
          fi
          
          next_version="${major}.${minor}.${patch}${patch_iter}"

          echo "Updating $this_version to $next_version"
          echo "this_version=$this_version" >> $GITHUB_OUTPUT
          echo "next_version=$next_version" >> $GITHUB_OUTPUT
      
      # Adds variables to github output for pull-request job
      # pull_request_create: { 0 | 1 } indicating if pull request should be automatically created
      # pull_request_branch: { branch-name } that the pull request will be made for
      - id: pull_request
        run: |
          pull_request_create=0
          pull_request_branch_source="${GITHUB_REF#refs/heads/}"
          pull_request_branch_target=""

          if [[ "${{ github.ref }}" = "refs/heads/main" ]]; then
            pull_request_create=0
          elif [[ "${{ github.ref }}" = "refs/heads/dev" ]]; then
            pull_request_branch_target="main"
            pull_request_create=1
          else
            pull_request_branch_target="dev"
            pull_request_create=1
          fi

          echo $pull_request_create
          echo $pull_request_branch_source
          echo $pull_request_branch_target

          echo "pull_request_create=$pull_request_create" >> $GITHUB_OUTPUT
          echo "pull_request_branch_source=$pull_request_branch_source" >> $GITHUB_OUTPUT
          echo "pull_request_branch_target=$pull_request_branch_target" >> $GITHUB_OUTPUT

  # create pr if upstream configured
  create_pull:

    if: needs.prepare.outputs.pull_request_create == '1'
    needs:
      - prepare

    uses: ./.github/workflows/create_pr.yml
    with:
      source_branch: ${{ needs.prepare.outputs.pull_request_branch_source }}
      target_branch: ${{ needs.prepare.outputs.pull_request_branch_target }}
      promotion_tag: 'promotion'
    secrets: inherit

  # create pr if upstream configured
  docker_build:

    if: needs.prepare.outputs.pull_request_create == '0'
    needs:
      - prepare
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/docker_build_push.yml
    with:
      tag: ${{ needs.prepare.outputs.next_version }}
      version: ${{ needs.prepare.outputs.next_version }}
      ignore_push: false
    secrets: inherit

  # create tag if build succeeds
  create-tag:

    if: needs.prepare.outputs.pull_request_create == '0'
    needs:
      - prepare
      - docker_build
      
    uses: ./.github/workflows/create_tag.yml
    with:
      version: ${{ needs.prepare.outputs.next_version }}
    secrets: inherit
