name: Pull Request Source Code Workflow

# Trigger on pull request events targeting the main branch and for specified paths
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    # paths:
    #   - "src/**"

jobs:
  # Job to run tests
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests.
        uses: ./.github/workflows/on_wfc_tests.yml

  # Job to build and push Docker images
  build-and-push-docker:
    name: Build and Push Docker Images
    needs: run-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build and Push Docker Images
        uses: ./.github/workflows/docker_build_push.yml
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
          build_tag: pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}

  # Job to dispatch deployment event
  dispatch-deployment:
    name: Dispatch Deployment Event
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Deployment Event
        uses: ./.github/workflows/on_wfc_dispatch_deployment.yml
        with:
          environment: ${{ github.event.pull_request.head.ref }}
          version: pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}
          dispatch_token: ${{ secrets.WF_DISPATCH_PYMP_INFRA_FLUX }}