name: on pr create and sync
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev
      - main

jobs:

  prepare:
    runs-on: ubuntu-latest
    outputs:
      this_version: ${{ steps.versions.outputs.this_version }}
      next_version: ${{ steps.versions.outputs.next_version }}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

  docker_build:

    permissions:
      contents: read
      packages: write
      
    uses: ./.github/workflows/docker_build_push.yml
    with:
      tag: ${{ github.event.pull_request.head.ref }}
      version: ${{ github.event.pull_request.head.ref }}
      ignore_push: true
    secrets: inherit