# name: on pr closed
# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - dev
#       - main

# jobs:

#   docker_build:

#     permissions:
#       contents: read
#       packages: write
      
#     uses: ./.github/workflows/docker_build_push.yml
#     with:
#       tag: ${{ github.event.pull_request.head.ref }}
#       version: ${{ github.event.pull_request.head.ref }}
#       ignore_push: false
#     secrets: inherit