name: on pr create and sync
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev
      - main

jobs:

  prepare:
    runs-on: ubuntu-latest
    outputs:
      this_version: ${{ steps.versions.outputs.this_version }}
      next_version: ${{ steps.versions.outputs.next_version }}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      
      # Adds variables related to version using output from git ls-remote
      # this_version: { semantic version } latest version from git ls-remote
      # next_version: { semantic version } latest version incremented based on branch name
      - id: versions
        shell: bash
        run: |
          this_version=$(git ls-remote --tag origin | cut -d '/' -f 3 | sort -V | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)

          major=$(echo $this_version | awk -F'.' '{print $1}')
          minor=$(echo $this_version | awk -F'.' '{print $2}')
          patch=$(echo $this_version | awk -F'.' '{print $3}')
          patch_iter=""

          if [[ "${{ github.ref }}" = "release" ]]; then
            major=$((major+1))
            minor=0
            patch=0
          elif [[ "${{ github.ref }}" = "main" ]]; then
            minor=$((minor+1))
            patch=0
          elif [[ "${{ github.ref }}" = "dev" ]]; then
            patch=$((patch+1))
          else
            patch_count=$(git ls-remote --tag origin | cut -d '/' -f 3 | sort -V | grep $major.$minor.$patch | wc -l)
            patch_iter="-$patch_count"
          fi
          
          next_version="${major}.${minor}.${patch}${patch_iter}"

          echo "Updating $this_version to $next_version"
          echo "this_version=$this_version" >> $GITHUB_OUTPUT
          echo "next_version=$next_version" >> $GITHUB_OUTPUT

  docker_build:

    permissions:
      contents: read
      packages: write

    needs:
      - prepare
    uses: ./.github/workflows/docker_build_push.yml
    with:
      tag: ${{ needs.prepare.outputs.next_version }}
      version: ${{ needs.prepare.outputs.next_version }}
    secrets: inherit

  create-tag:
    needs:
      - prepare
      - docker_build
    uses: ./.github/workflows/create_tag.yml
    with:
      version: ${{ needs.prepare.outputs.next_version }}
    secrets: inherit