name: 'on pr open'

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - dev
      - main

jobs:  
  # run tests
  tests:
    uses: ./.github/workflows/on_wfc_tests.yml
    secrets: inherit
