name: 'on wfc tests'

on: 
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: 
        image:
          - pymp_core
          - pymp_server

    steps:
      - 
        uses: actions/checkout@v3 
      - 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip' # caching pip dependencies
      -
        run: |
          pip install -r ./src/${{ matrix.image }}/requirements.txt
          pip install ./src/${{ matrix.image }}
          pip install -r ./src/${{ matrix.image }}_tests/requirements.txt
      -
        run: |
          pytest ./src/p${{ matrix.image }}_tests
