name: 'on wfc tests'

on: 
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - 
        uses: actions/checkout@v3 
      - 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip' # caching pip dependencies
      -
        run: |
          pip install -r ./src/pymp_core/requirements.txt
          pip install ./src/pymp_core
          pip install -r ./src/pymp_core_tests/requirements.txt
      -
        run: |
          pytest ./src/pymp_core_tests
